version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlite:./prisma/dev.db
    volumes:
      - ./backend/prisma:/app/prisma
    depends_on:
      - database


